### ISSUE TITLE
Is makemigrations really necessary?

### ISSUE THREAD

**Issue by ranit-appcode** [lucacitta/Django-GlobalPlaces#3]
The [README](https://github.com/lucacitta/Django-GlobalPlaces/blob/main/README.md) states that you need to run both `makemigrations` and `migrate`, but is it really needed? Since the library already comes with migrations (as it should), I think a `migrate` should be enough.

**Comment by lucacitta** [comment]
Its not realy, i was needed in a previus version. I will update it!
